server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mugon-dev/microservice-config.git
          ignore-local-ssh-settings: true
          host-key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          host-key-algorithm: ecdsa-sha2-nistp256
          private-key: |
                        -----BEGIN EC PRIVATE KEY-----
                        MHcCAQEEIKdvy19LJfC8UbYJRoSl8dGXijOMaJS1dEShvJ2VMOqBoAoGCCqGSM49
                        AwEHoUQDQgAE4fwbiwiVUNSVAxrQJ54T0KrgJbUPJIDJVeLJstyu0GLdzIXCy7dI
                        L8QSAMfyNpTkXlfV+svAX+HXbjocWxGY9A==
                        -----END EC PRIVATE KEY-----

          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh